version: '{build}-{branch}'

os: Default Azure
platform:
  - x64

environment:
  matrix:
    - ruby_version: "22"

init:
- ps: |
    [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }

install:
- ps: |
    choco install virtualbox --version 5.1.22
    choco install vagrant --version 1.9.5
    iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
    cd $env:APPVEYOR_BUILD_FOLDER
- netsh winsock reset
- refreshenv
- scoop install shellcheck
- refreshenv
- ps: Restart-Computer -Force
- vagrant -v
- VBoxManage -v
- ssh -V
- ipconfig /all
- ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
- ps: gem install bundler --quiet --no-ri --no-rdoc
build_script:
- ps: Test-NetConnection google.com -Port 80
test_script:
- shellcheck (Get-ChildItem .\*.sh | Select-Object -Expand FullName)
- shellcheck (Get-ChildItem .\tests\*.sh | Select-Object -Expand FullName)
- ps: sh tests/tests.sh